name: Bump version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: windows-latest
#    if: startsWith(github.event.head_commit.message , 'feat:') || startsWith(github.event.head_commit.message, 'fix:')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.name "Mateusz Woda"
          git config --global user.email "mwoda@box.com"
      - shell: pwsh
        name: Bump version
        env:
          GithubToken: ${{ secrets.GH_TOKEN }}
        run: .\build\bump_version.ps1 -dr $false
