name: Bump version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.name "Mateusz Woda"
          git config --global user.email "mwoda@box.com"
      - name: Bump version
        run: .\build\bump_version.ps1 -dr $false -gh ${{ secrets.GH_TOKEN }}